### ISSUE TITLE
Add a CODE_OF_CONDUCT.md file using WeAllBehave

### ISSUE THREAD

**Issue by klauskpm** [klauskpm/cz-simple-changelog#2]
# Description
This project needs a CODE_OF_CONDUCT and it would be better if it was easy to update. That's why I'd like to use the [WeAllBehave](https://github.com/WeAllJS/weallbehave) package.

## Tasks
- [ ] install the package
- [ ] add `update-coc` to the package.json scripts
- [ ] generate CODE_OF_CONDUCT.md

## 🥇 Call dibs 
Say you will do this issue. I don't need to give you permission, but, if someone called dibs first and you send your PR after that, I will tag your PR as invalid.

Respect the dibs 👊

**Comment by ClaraTersi** [comment]
I will work on this :)

**Comment by klauskpm** [comment]
Go on! Good hacktoberfest! 🎉
