### ISSUE TITLE
Add a CONTRIBUTING.md file using WeAllContribute

### ISSUE THREAD

**Issue by klauskpm** [klauskpm/cz-simple-changelog#3]
# Description
This project needs a CONTRIBUTING file and it would be better if it was easy to update. That's why I'd like to use the [WeAllContribute](https://github.com/WeAllJS/weallcontribute) package.

## Tasks
- [x] install the package
- [x] add `update-contrib` to the package.json scripts
- [x] generate CONTRIBUTING.md

## 🥇 Call dibs 
Say you will do this issue. I don't need to give you permission, but, if someone called dibs first and you send your PR after that, I will tag your PR as invalid.

Respect the dibs 👊

**Comment by klauskpm** [comment]
This issue was closed by #7 @rrrahal .
Thank you and happy Hacktoberfest! 🎉
